name: Generate Signing Key

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -keystore animetail.keystore \
            -alias animetail \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass animetail123 \
            -keypass animetail123 \
            -dname "CN=Animetail, OU=Android, O=Animetail, L=NA, S=NA, C=IN"

      - name: Convert keystore to Base64
        run: |
          base64 animetail.keystore > signing_key.txt

      - name: Upload Base64 key
        uses: actions/upload-artifact@v4
        with:
          name: signing-key
          path: signing_key.txt
